version: '3'
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - sky-lark
  sky-lark:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 5314:5314
